ARG IMAGE=bullseye
FROM mcr.microsoft.com/devcontainers/${IMAGE}

# [Choice] Node.js version: lts/*, 16, 14, 12, 10
#ARG NODE_VERSION="lts/*"
#RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"
